export type ClaimStatus = 'OK' | 'INFO';
export type EvidenceKind = 'code' | 'report' | 'image';

export interface Bilingual { en: string; pt: string; }

/** Authored input: where the proof lives in the Aurora repo. */
export interface ClaimSource {
  /** repo-relative path from AURORA_REPO_ROOT */
  path: string;
  /** optional [startLine, endLine] (1-based, inclusive) excerpt window */
  lines?: [number, number];
  /** short badge label, e.g. "lib/trustware" */
  label: string;
}

/** Generated by harvest. */
export interface Provenance {
  sourcePath: string;
  sha256: string;
  commit: string;     // short SHA
  timestamp: string;  // ISO; last-commit date of the file
  asset: string;      // path under /evidence/*
  kind: EvidenceKind;
}

export interface Claim {
  id: string;
  index: string;            // "01".."06"
  title: Bilingual;
  status: ClaimStatus;
  tier: 'primary' | 'secondary';
  colSpan: number;          // md grid span: 5,7,4,8,6,6
  source: ClaimSource;
  caption?: Bilingual;      // "what this proves"
}

export function isBilingual(v: unknown): v is Bilingual {
  return !!v && typeof v === 'object'
    && typeof (v as Bilingual).en === 'string'
    && typeof (v as Bilingual).pt === 'string';
}

export function isClaim(v: unknown): v is Claim {
  if (!v || typeof v !== 'object') return false;
  const c = v as Claim;
  return typeof c.id === 'string'
    && typeof c.index === 'string'
    && (c.tier === 'primary' || c.tier === 'secondary')
    && typeof c.colSpan === 'number'
    && (c.status === 'OK' || c.status === 'INFO')
    && isBilingual(c.title)
    && !!c.source && typeof c.source.path === 'string' && typeof c.source.label === 'string';
}
